config/routes.rb
Rails.application.routes.draw do
  root to: 'courses#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :courses, only: [:index] do
    resources :lessons, only: :index
    resources :participants, only: :index
    resource  :subscriptions, only: [:create, :destroy], controller: :course_subscriptions
  end

  namespace :users do
    resource :blacklist, only: [:create, :destroy], controller: :course_bans
    resource  :profile, only: [:edit, :update], controller: :profile
    resources :participated_courses, only: :index, controller: :participated_courses
    resources :courses do
      resources :lessons do
        resources :hometasks
      end
    end
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def index
    @users = course.participants.includes(:profile)
  end

  private

  def course
    @course ||= Course.find(params[:course_id])
  end
  helper_method :course
end

app/views/participants/_participant.html.haml
%tr{id: "course-participant-#{user.id}"}
  %td= "#{user.first_name} #{user.last_name}"
  %td
    - if user_signed_in? && user.id == current_user.id
      #unsubscribe-button{ style: ('display: none' if current_user.banned_in?(course)) }
        = link_to 'Unsubscribe', course_subscriptions_path(course), method: :delete, remote: true
    - if user_signed_in? && current_user.id == course.user.id
      #ban-button{ style: ('display: none' if user.banned_in?(course)) }
        = link_to "Ban", users_blacklist_path(course_id: course.id, user_id: user.id), method: :post, remote: true
      #unban{ style: ('display: none' if not user.banned_in?(course)) }
        %p banned 
        = link_to "Unban", users_blacklist_path(course_id: course.id, user_id: user.id), method: :delete, remote: true

app/views/participants/index.html.haml
%h1 Course #{@course.title} participants

- if user_signed_in? && current_user.id != course.user.id
  #subscription-button{ style: ('display: none' if current_user.participate_in?(course)) }
    = link_to 'Subscribe', course_subscriptions_path(course), method: :post, remote: true

%table.table.table-bbordered
  %tbody#participants-list
    %tr
      %th User
      %th Action
    - @users.each do |user|
      =render 'participant', course: course, user: user 