config/routes.rb
Rails.application.routes.draw do
  root to: 'courses#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :courses, only: [:index] do
    resources :lessons, only: :index
    resources :participants, only: :index
    resource  :subscriptions, only: [:create, :destroy], controller: :course_subscriptions
  end

  namespace :users do
    resource :blacklist, only: [:create, :destroy], controller: :course_bans
    resource  :profile, only: [:edit, :update], controller: :profile
    resources :participated_courses, only: :index, controller: :participated_courses
    resources :courses do
      resources :lessons do
        resources :hometasks
      end
    end
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  acts_as_list

  mount_uploader :picture, LessonPictureUploader

  belongs_to :course
  has_many :hometasks

  validates :title, presence: true, length: { maximum: 20 }
  validates :description, presence: true, length: { maximum: 100 }
  validates :home_task, presence: true

  scope :visible, -> { where(hiden: false) }

  scope :sorted, -> { order('lessons.position ASC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  resourcify

  rolify

  include Omniauthable

  after_create :create_user_profile

  after_create :assign_default_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :twitter]

  has_one :profile, dependent: :destroy
  has_many :authored_courses, class_name: 'Course', foreign_key: :user_id
  has_many :social_profiles
  has_many :course_users, dependent: :destroy
  has_many :participated_courses, through: :course_users, source: :course

  accepts_nested_attributes_for :profile

  delegate :first_name, :last_name, to: :profile, allow_nil: true

  def participate_in?(course)
    course_users.exists?(course_id: course.id)
  end

  def banned_in?(course)
    course_users.where(kick: true).exists?(course_id: course.id)
  end

  private

  def assign_default_role
    add_role(:user) if roles.blank?
  end

  def create_user_profile
    build_profile
    profile.save(validates: false)
  end
end

app/controllers/api/v1/user/base_controller.rb
class Api::V1::User::BaseController < Api::V1::BaseController
	before_filter :authenticate_user!

	private

	def authenticate_user!
    user = User.find_by(authentication_token: params[:auth_token])
    if user.present?
      sign_in user, store: false
    else
      raise NotAuthorized
    end
  end
end

app/controllers/api/v1/user/courses_controller.rb
class Api::V1::User::CoursesController < Api::V1::User::BaseController
	def index
		courses = current_user.authored_courses
		respond_with_success courses
	end
end

app/controllers/api/v1/user/participated_courses_controller.rb
class Api::V1::User::ParticipatedCoursesController < Api::V1::User::BaseController
  def index
    courses = current_user.participated_courses
    respond_with_success courses
  end
end

app/controllers/api/v1/user/subscriptions_controller.rb
class Api::V1::User::SubscriptionsController < Api::V1::User::ProfilesController
  before_filter :authenticate_user!
  before_action :deny_access, only: [:create, :destroy] if :banned?

  def index
    participated_courses = current_user.participated_courses
    respond_with_success(participated_courses)
  end

  def create
    course.subscribers << current_user

    render json: { success: true, message: 'Successfully subscribed!' }, status: 201
  end

  def destroy
    authorize! :unsubscribe, @course
    course.course_users.find_by(user_id: current_user.id).destroy!

    render json: { success: true, message: 'Successfully unsubscribed!' }, status: 202
  end

  private

  def course
    @course ||= Course.find(params[:course_id])
  end
  helper_method :course

  def deny_access
    redirect_to root_path, notice: 'You are banned.'
  end

  def banned?
    current_user.course_users.where(kick: true).exists?(course_id: course.id)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :course
  load_and_authorize_resource :lesson, through: :course

  def index
    @lessons = course.lessons.visible
  end

  private

  def course
    @course ||= Course.find(params[:course_id])
  end
end

app/controllers/users/base_controller.rb
class Users::BaseController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/users/course_bans_controller.rb
class Users::CourseBansController < Users::BaseController
  before_action :ban_user

  def create
    ban_user.update_attribute(:kick, true) if @course_user
  end

  def destroy
    ban_user.update_attribute(:kick, false) if @course_user
  end

  private

  def course
    @course ||= current_user.authored_courses.find(params[:course_id])
  end
  helper_method :course

  def user
    @user ||= User.find(params[:user_id])
  end
  helper_method :user

  def ban_user
    @course_user = CourseUser.where(course_id: params[:course_id], user_id: params[:user_id]).first
  end
end

app/controllers/users/courses_controller.rb
class Users::CoursesController < Users::BaseController
  PER_PAGE = 3

  before_action :find_course, only: [:edit, :update, :show, :destroy]

  authorize_resource

  def index
    @courses = current_user.authored_courses.page(params[:page]).per(params[:per_page] || PER_PAGE)
  end

  def new
    @course = current_user.authored_courses.build
  end

  def create
    @course = current_user.authored_courses.build(courses_params)

    if @course.save
      redirect_to users_courses_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @course.update(courses_params)
      redirect_to users_courses_path
    else
      render :edit
    end
  end

  def show
    @lessons = find_course.lessons.sorted.page(params[:page]).per(params[:per_page] || PER_PAGE)
  end

  def destroy
    @course.destroy

    redirect_to users_courses_path
  end

  private

  def find_course
    @course = current_user.authored_courses.find(params[:id])
  end
  helper_method :find_course

  def courses_params
    params.require(:course).permit(:title, :picture, :hiden)
  end
end

app/controllers/users/hometasks_controller.rb
class Users::HometasksController < Users::BaseController
  def index
    @hometasks = lesson.hometasks
    @hometask = lesson.hometasks.build
  end

  def new
    @hometask = lesson.hometasks.build
  end

  def create
    @hometask = lesson.hometasks.build(hometask_params)

    if @hometask.save
      flash[:success] = 'Hometask successfully sent.'
      redirect_to users_course_lesson_hometasks_path
    else
      render :new
    end
  end

  private

  def course
    @course ||= Course.find(params[:course_id])
  end
  helper_method :course

  def lesson
    @lesson ||= Lesson.find(params[:lesson_id])
  end
  helper_method :lesson

  def hometask_params
    params.require(:hometask).permit(:name, :hometask)
  end
end

app/controllers/users/lessons_controller.rb
class Users::LessonsController < Users::BaseController
  before_action :course, :find_lesson, only: [:edit, :update, :destroy]
  authorize_resource

  def new
    @lesson = course.lessons.new
    @lesson_count = course.lessons.count + 1
  end

  def create
    @lesson = course.lessons.new(lesson_params)

    if @lesson.save
      flash[:success] = 'Lesson was successsfull created.'
      redirect_to users_course_path(@course)
    else
      @lesson_count = @lesson.count + 1
      render :new
    end
  end

  def edit
    @lesson_count = course.lessons.count
  end

  def update
    if @lesson.update(lesson_params)
      flash[:success] = 'Lesson was updated.'
      redirect_to users_course_path(find_course)
    else
      @lesson_count = find_lesson.count
      render :edit
    end
  end

  def destroy
    @lesson.destroy
    redirect_to users_course_path(@course)
  end

  private

  def course
    @course = Course.find(params[:course_id])
  end

  def find_lesson
    @lesson = @course.lessons.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :position, :description, :lecture_notes, :picture, :home_task)
  end
end

app/controllers/users/participated_courses_controller.rb
class Users::ParticipatedCoursesController < Users::BaseController
  PER_PAGE = 3

  def index
    @courses = current_user.participated_courses.recent.page(params[:page]).per(params[:per_page] || PER_PAGE)
  end
end

app/controllers/users/profile_controller.rb
class Users::ProfileController < Users::BaseController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to users_courses_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 profile_attributes: [:first_name, :last_name])
  end
end

app/views/users/lessons/_form.html.haml
= simple_form_for [@course, @lesson], :url => for_action, html: {multipart: true} do |f|
  .border-top.border-bottom{:style => "overflow:hidden"}
    .form-inputs.col-md-6.border-right
      %h2 Main info
      = f.input :title, :label => "Title"
      = f.input :description, :label => "Lesson description"
      = f.select(:position, 1..@lesson_count)
      = f.input :lecture_notes, :label => "Lecture notes"
      = f.input :home_task, :label => "Home work"
      = f.input :hiden, as: :boolean
      .container.col-md-12
        %p.left Picture
        = f.file_field :picture, :label => "Image", :class => 'right'
    .form-inputs.col-md-6
  .right
    = link_to 'Back', url_for(:back), :class => 'btn btn-default  rating-item-btn'
    = f.submit :class => 'btn btn-success  rating-item-btn'

app/views/users/lessons/_lesson.html.haml
%li.container
  .col-md-2
    = image_tag lesson.picture.thumb
  .col-md-2
    %h4= lesson.title
  .row
    .col-md-2
      = lesson.description
  .col-md-2
    = lesson.lecture_notes
  .col-md-2
    = lesson.home_task
  .col-md-2
    - if user_signed_in? && current_user.id = @course.user.id
      = link_to 'Show Homeworks', users_course_lesson_hometasks_path(@course, lesson), class: "btn btn-primary"
    = link_to "Edit", edit_users_course_lesson_path(@course, lesson), :class => 'btn btn-success btn-xs'
    = link_to "Destroy", users_course_lesson_path(@course, lesson), :method => :delete, data: { :confirm => "Are you sure?" }, :class => 'btn btn-danger btn-xs'

app/views/users/lessons/edit.html.haml
%h1
  Edit #{@lesson.title}
= render :partial => 'form', :locals => { :for_action => users_course_lesson_path(@course, @lesson) }

app/views/users/lessons/index.html.haml
.ratings_heading
  %h1.rating-h1= @course.title
  = link_to 'Add lesson', new_users_course_lesson_path(@course), :class => "btn btn-success right"
.margin-top-10
  - if @lessons.present?
    .content
      .row
        %table.pretty.table.table-bordered
          %tbody
            %tr
              %th Cover 
              %th Title
              %th
                Lesson
                %br>/
                Date
              %th Description
              %th Summary
              %th Homework
              %th Action
            - @lessons.each do |lesson|
              %tr
                %td
                  = image_tag lesson.picture.thumb
                %td
                  = lesson.title
                %td 
                  = lesson.date_of
                %td
                  = lesson.description
                %td
                  = lesson.lecture_notes
                %td
                  = lesson.home_task
                %td
                  - if user_signed_in? && @course.user.id == current_user.id
                    = link_to "Edit", edit_users_course_lesson_path(@course, lesson), :class => 'btn btn-success btn-sm'
                    = link_to "Destroy", users_course_lesson_path(@course, lesson), :method => :delete, data: { :confirm => "Are you sure?" }, :class => 'btn btn-danger btn-sm'
                  = link_to 'Show Homeworks', users_course_lesson_hometasks_path(@course, lesson), class: "btn btn-primary btn-sm"
    = link_to 'Back', url_for(:back), :class => 'btn btn-default'
  - else
    %h2.rating-h1 You don't have lessons now.

app/views/users/lessons/new.html.haml
%h1 New lesson
= render :partial => 'form', :locals => { :for_action => users_course_lessons_path(@course) }