config/routes.rb
Rails.application.routes.draw do
  root to: 'courses#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :courses, only: [:index] do
    resources :lessons, only: :index
    resources :participants, only: :index
    resource  :subscriptions, only: [:create, :destroy], controller: :course_subscriptions
  end

  namespace :users do
    resource :blacklist, only: [:create, :destroy], controller: :course_bans
    resource  :profile, only: [:edit, :update], controller: :profile
    resources :participated_courses, only: :index, controller: :participated_courses
    resources :courses do
      resources :lessons do
        resources :hometasks
      end
    end
  end
end

app/controllers/api/v1/courses_controller.rb
class Api::V1::CoursesController < Api::V1::BaseController
	def index
		courses = Course.all 
		respond_with_success courses
	end
end

app/controllers/api/v1/user/courses_controller.rb
class Api::V1::User::CoursesController < Api::V1::User::BaseController
	def index
		courses = current_user.authored_courses
		respond_with_success courses
	end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  PER_PAGE = 3

  def index
    @courses = Course.recent.visible.page(params[:page]).per(params[:per_page] || PER_PAGE)
  end

  private

  def course
    @course ||= Course.find(params[:id])
  end
  helper_method :course
end

app/controllers/users/courses_controller.rb
class Users::CoursesController < Users::BaseController
  PER_PAGE = 3

  before_action :find_course, only: [:edit, :update, :show, :destroy]

  authorize_resource

  def index
    @courses = current_user.authored_courses.page(params[:page]).per(params[:per_page] || PER_PAGE)
  end

  def new
    @course = current_user.authored_courses.build
  end

  def create
    @course = current_user.authored_courses.build(courses_params)

    if @course.save
      redirect_to users_courses_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @course.update(courses_params)
      redirect_to users_courses_path
    else
      render :edit
    end
  end

  def show
    @lessons = find_course.lessons.sorted.page(params[:page]).per(params[:per_page] || PER_PAGE)
  end

  def destroy
    @course.destroy

    redirect_to users_courses_path
  end

  private

  def find_course
    @course = current_user.authored_courses.find(params[:id])
  end
  helper_method :find_course

  def courses_params
    params.require(:course).permit(:title, :picture, :hiden)
  end
end

app/views/courses/index.html.haml
.content
  .row
    .col-md-12
      - if @courses.present?
        .container
          - @courses.each do |course|
            .col-md-3
              .thumbnail
                - if current_user.participate_in?(course) && !current_user.banned_in?(course)
                  = link_to course.title.humanize, course_lessons_path(@lesson, course_id: course.id)
                - else 
                  = course.title.humanize
                %br
                = image_tag course.picture.admin_thumb
                - if current_user.try(:banned_in?, course)
                  %p You are deducted
                - else
                  %br
                  = link_to 'Participants', course_participants_path(course)
        .row
          .col-md-offset-5
            = paginate @courses
      - else
        %h2 No courses

app/views/courses/show.html.haml
.margin-top-10
  - if @lessons.present?
    %ol.list-group= render @lessons
    = link_to 'Back', url_for(:back), :class => 'btn btn-default'
  - else
    %h2.rating-h1 You don't have lessons now.