config/routes.rb
Rails.application.routes.draw do
  root to: 'courses#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :courses, only: [:index] do
    resources :lessons, only: :index
    resources :participants, only: :index
    resource  :subscriptions, only: [:create, :destroy], controller: :course_subscriptions
  end

  namespace :users do
    resource :blacklist, only: [:create, :destroy], controller: :course_bans
    resource  :profile, only: [:edit, :update], controller: :profile
    resources :participated_courses, only: :index, controller: :participated_courses
    resources :courses do
      resources :lessons do
        resources :hometasks
      end
    end
  end
end

app/views/layouts/partials/_footer.html.haml
%footer.main-footer
  .pull-right.hidden-xs
    %b Version
    0.0.1
  %strong
    Copyright © Rubyboost 2016

app/views/layouts/partials/_header.html.haml
%header.main-header
  / Logo
  %a.logo{:href => root_path}
    / mini logo for sidebar mini 50x50 pixels
    %span.logo-mini JET
    / logo for regular state and mobile devices
    %span.logo-lg JetCourses
  / Header Navbar: style can be found in header.less
  %nav.navbar.navbar-static-top{:role => "navigation"}
    / Sidebar toggle button
    %a.sidebar-toggle{"data-toggle" => "offcanvas", :href => "#", :role => "button"}
      %span.sr-only Toggle navigation
    .navbar-custom-menu
      %ul.nav.navbar-nav
        - if user_signed_in?
          / Messages: style can be found in dropdown.less
          / User Account: style can be found in dropdown.less
          %li.user.user-menu
            = link_to users_courses_path do
              = image_tag 'user2-160x160.jpg', class: 'user-image', alt: 'User Image'
              %span.hidden-xs= current_user.first_name
          %li.user.user-menu
            = link_to destroy_user_session_path, method: :delete, class: 'btn' do
              %span.hidden-xs Sign Out
        - else
          %li.user.user-menu
            = link_to new_user_registration_path, class: 'btn' do
              %span.hidden-xs Sign Up
          %li.user.user-menu
            = link_to new_user_session_path, class: 'btn' do
              %span.hidden-xs Sign In

app/views/layouts/partials/_sidebar.html.haml
/ Left side column. contains the logo and sidebar
%aside.main-sidebar
  / sidebar: style can be found in sidebar.less
  %section.sidebar
    - if user_signed_in?
      / Sidebar user panel
      .user-panel
        .pull-left.image
          = image_tag 'user2-160x160.jpg', class: 'img-circle'
        .pull-left.info
          %p= current_user.first_name
          %a{:href => "#"}
            %i.fa.fa-circle.text-success
            Online
    / search form
    %form.sidebar-form{:action => "#", :method => "get"}
      .input-group
        %input.form-control{:name => "q", :placeholder => "Search...", :type => "text"}/
        %span.input-group-btn
          %button#search-btn.btn.btn-flat{:name => "search", :type => "submit"}
            %i.fa.fa-search
    / /.search form
    / sidebar menu: : style can be found in sidebar.less
    %ul.sidebar-menu
      %li.header MAIN NAVIGATION
      %li.active
        = link_to root_path do
          %i.fa.fa-dashboard
          %span Dashboard
          %i.fa.fa-angle-left.pull-right
      %li
        = link_to courses_path do
          %i.fa.fa-files-o
          %span Courses
      - if user_signed_in?
        %li 
          =link_to edit_users_profile_path do
            %i.fa.fa-user
            %span Edit profile
        %li
          =link_to users_participated_courses_path do
            %i.fa.fa-files-o
            %span Participated Courses
      - if current_user && current_user.has_role?(:trainer)
        %li
          =link_to users_courses_path do
            %i.fa.fa-files-o
            %span My Courses
  / /.sidebar
/ Content Wrapper. Contains page content